# Generated by Django 3.0.5 on 2020-04-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('scale', 'Scale'), ('arpeggio', 'Arpeggio'), ('chord', 'Chord')], max_length=25)),
                ('note', models.CharField(choices=[('C', 'C'), ('C', 'C#'), ('D', 'D'), ('D#', 'D#'), ('E', 'E'), ('F', 'F'), ('F#', 'F#'), ('G', 'G'), ('G#', 'G#'), ('A', 'A'), ('A#', 'A#'), ('B', 'B')], max_length=2)),
                ('quality', models.CharField(choices=[('major', 'Major Triad'), ('minor', 'Minor Triad'), ('diminished_triad', 'Diminished Triad'), ('major7', 'Major 7th'), ('dominant', 'Dominant 7th'), ('minor7', 'Minor 7th'), ('half-diminished', 'Half-diminished 7th'), ('diminished7', 'Diminished 7th')], max_length=25)),
            ],
            options={
                'unique_together': {('type', 'note', 'quality')},
            },
        ),
    ]
